# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2adf97bb4fcc202249a6ee9b1bc3c11856074bddd56ad2cd309488374814bfcdb77320d0deaed69d666824e9bd02a2cbf9a65e3bce33615d8e9c6a6046e222e

test:
  secret_key_base: 9960415bb5dd7c7f0d6bfe0169e4dd46e8bc2ab67f0662c25efdb692ca872c33a6d4dec0049e778d95d56865f91afc5fe47a6ef6348118f6bf3ab673e58f7af8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
